{% set name = "string2string" %}
{% set version = "0.0.152" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/string2string-{{ version }}.tar.gz
  sha256: 40a5b5fd01a0dcc42cc132fb431b0086bd3d73a123db25bcbdf315d7a0c55d78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pytorch
    - numpy
    - transformers
    - datasets
    - faiss-cpu
    - bert_score
    - fasttext
    - pandas
    - joblib
    - sacrebleu
    - rouge-score
    - networkx

test:
  source_files:
    - tests
  imports:
    - string2string
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests/test_alignment.py
    - pytest -vvv --capture=tee-sys tests/test_distance.py
    - pytest -vvv --capture=tee-sys tests/test_search.py
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/stanfordnlp/string2string
  summary: String-to-String Algorithms for Natural Language Processing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
