{% set name = "string2string" %}
{% set version = "0.0.150" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/string2string-{{ version }}.tar.gz
  sha256: c9773ff0449aadc4a8a5dd48a8448b536f38cb5564820a4ad98b39a12e805bfc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch
    - numpy
    - transformers
    - datasets
    - faiss-cpu ==1.7.3
    - bert_score
    - fasttext
    - pandas
    - joblib

test:
  source_files:
    - tests
  imports:
    - string2string
  commands:
    - pytest -vvv --capture=tee-sys tests/test_alignment.py
    - pytest -vvv --capture=tee-sys tests/test_distance.py
    - pytest -vvv --capture=tee-sys tests/test_search.py
  requires:
    - pytest

about:
  home: https://github.com/stanfordnlp/string2string
  summary: String-to-String Algorithms for Natural Language Processing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
